name: Build and Deploy to EKS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: tsimagnova/eks-app
      IMAGE_TAG: python-app-1
      AWS_DEFAULT_REGION: us-east-1
      EKS_CONTAINER_NAME: fenelin
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker@v2
      with:
        version: '20.10.16' # Update to the desired Docker version

    - name: Login to Docker Registry
      run: docker login -u ${{ secrets.REGISTRY_USER }} -p ${{ secrets.REGISTRY_PASS }}
